import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * DockStart Documentation —— 侧边栏草稿
 *
 * 机制：autogenerated sidebar（自动生成侧边栏）。
 *
 * 章节标题、层级、顺序与展开状态全部由目录结构本身决定，不需要在本文件里
 * 逐个登记页面：
 *   - 分类标题 / 顺序 / 是否默认展开：各目录下的 `_category_.json`
 *   - 同目录内页面的先后顺序：各页 front matter 里的 `sidebar_position`
 *
 * 因此新增页面时只需要创建 Markdown 并写好 front matter，sidebar 会自动更新。
 *
 * ⚠️ 本文件是草稿，尚未经过真实的 `docusaurus build` 验证（当前未安装依赖）。
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
