#!/usr/bin/env node
/**
 * DockStart Documentation —— 本地文档结构检查
 *
 * 在尚未安装 Docusaurus 依赖的情况下，对 docs/ 做一次静态结构体检：
 *   1. 每个分类目录是否有 _category_.json，JSON 是否合法，label / position 是否齐全
 *   2. 每个 Markdown 是否带 YAML front matter 与 title
 *   3. 同一目录内 sidebar_position 是否唯一
 *   4. 站点内 title 是否重复
 *   5. 站内链接（相对 .md 链接、/docs/... 绝对链接）是否指向真实文件
 *   6. 打印按 autogenerated sidebar 顺序推导出的层级预览
 *
 * 用法：
 *   node scripts/check-docs.mjs
 *   node scripts/check-docs.mjs --quiet    只打印问题与汇总
 *   node scripts/check-docs.mjs --tree     额外打印完整 sidebar 预览
 *
 * 退出码：0 = 通过（可能有 warning）；1 = 存在 error。
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_DOCS = path.join(ROOT, 'docs');
const ENGLISH = process.argv.includes('--locale=en');
const DOCS = ENGLISH ? path.join(ROOT, 'i18n/en/docusaurus-plugin-content-docs/current') : SOURCE_DOCS;
const QUIET = process.argv.includes('--quiet');
const SHOW_TREE = process.argv.includes('--tree') || !QUIET;

const errors = [];
const warnings = [];
const fail = (m) => errors.push(m);
const warn = (m) => warnings.push(m);
const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/');

if (!fs.existsSync(DOCS)) {
  console.error(`[FATAL] 找不到 docs 目录：${DOCS}`);
  process.exit(1);
}

/* ----------------------------- front matter ----------------------------- */

function readFrontMatter(file, text) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text);
  if (!m) {
    fail(`${rel(file)}：缺少 YAML front matter（文件应以 --- 开头）`);
    return {};
  }
  const data = {};
  for (const rawLine of m[1].split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const i = line.indexOf(':');
    if (i === -1) {
      fail(`${rel(file)}：front matter 行无法解析 -> ${line}`);
      continue;
    }
    const key = line.slice(0, i).trim();
    let value = line.slice(i + 1).trim();
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    data[key] = value;
  }
  return data;
}

/* -------------------------------- 遍历 --------------------------------- */

/** @type {Map<string, {title: string, position: number}>} */
const docs = new Map();
/** @type {Map<string, any>} */
const categories = new Map();

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const mdFiles = entries.filter((e) => e.isFile() && /\.(md|mdx)$/i.test(e.name));
  const subDirs = entries.filter((e) => e.isDirectory());
  const positionSeen = new Map();

  for (const f of mdFiles) {
    const full = path.join(dir, f.name);
    const data = readFrontMatter(full, fs.readFileSync(full, 'utf8'));

    if (!data.title || !data.title.trim()) {
      fail(`${rel(full)}：front matter 缺少 title`);
    }

    let position = Number.MAX_SAFE_INTEGER;
    const posRaw = data.sidebar_position;
    if (posRaw === undefined) {
      warn(`${rel(full)}：未设置 sidebar_position，将按字母序排在目录末尾`);
    } else if (!/^\d+$/.test(posRaw)) {
      fail(`${rel(full)}：sidebar_position 必须是非负整数 -> ${posRaw}`);
    } else {
      position = Number(posRaw);
      if (positionSeen.has(position)) {
        fail(
          `${rel(full)}：sidebar_position ${position} 与 ${rel(positionSeen.get(position))} 冲突`,
        );
      } else {
        positionSeen.set(position, full);
      }
    }

    docs.set(full, { title: data.title, sidebarLabel: data.sidebar_label, position });
  }

  if (dir !== DOCS) {
    // Docusaurus uses the source category metadata for translated docs.
    const catPath = path.join(ENGLISH ? path.join(SOURCE_DOCS, path.relative(DOCS, dir)) : dir, '_category_.json');
    if (!fs.existsSync(catPath)) {
      fail(`${rel(dir)}：目录缺少 _category_.json`);
    } else {
      let json = null;
      try {
        json = JSON.parse(fs.readFileSync(catPath, 'utf8'));
      } catch (e) {
        fail(`${rel(catPath)}：JSON 解析失败 -> ${e.message}`);
      }
      if (json) {
        if (typeof json.label !== 'string' || !json.label.trim()) {
          fail(`${rel(catPath)}：缺少 label`);
        }
        if (!Number.isInteger(json.position)) {
          fail(`${rel(catPath)}：position 必须是整数`);
        }
        if (json.link && json.link.type !== 'generated-index') {
          warn(`${rel(catPath)}：link.type = ${json.link.type}（当前只校验 generated-index）`);
        }
        categories.set(dir, json);
      }
    }
  }

  if (!mdFiles.length && !subDirs.length) {
    fail(`${rel(dir)}：空目录`);
  }

  for (const d of subDirs) walk(path.join(dir, d.name));
}

walk(DOCS);

/* ---------------------------- title 重复检查 ---------------------------- */

const byTitle = new Map();
for (const [full, info] of docs) {
  if (!byTitle.has(info.title)) byTitle.set(info.title, []);
  byTitle.get(info.title).push(full);
}
for (const [title, list] of byTitle) {
  if (list.length > 1) {
    fail(`title 重复（${title}）：${list.map(rel).join(' , ')}`);
  }
}

/* ------------------------------ 链接检查 ------------------------------- */

function docTargetExists(relFromDocs) {
  const base = path.join(DOCS, relFromDocs);
  return (
    fs.existsSync(base) ||
    fs.existsSync(`${base}.md`) ||
    fs.existsSync(`${base}.mdx`) ||
    fs.existsSync(path.join(base, 'index.md')) ||
    fs.existsSync(path.join(base, 'index.mdx'))
  );
}

let internalLinks = 0;
let externalLinks = 0;
let imageLinks = 0;

const STATIC = path.join(ROOT, 'static');
// 捕获组 1 用于区分图片（![...]）与普通链接（[...]）
const LINK_RE = /(!?)\[([^\]]*)\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;

/**
 * 去掉围栏代码块与行内代码后再做链接扫描。
 *
 * Markdown / MDX 不会在代码里解析链接，所以代码块中的化学表达式不该被当成
 * 链接目标。典型例子是 SMILES —— `...CC[NH+](C)CC...` 会被朴素的
 * `[...](...)` 正则读成"链接到 C"，产生
 * 「站内相对链接失效 -> C」的误报。
 */
function stripCode(text) {
  return text
    .replace(/^(?:```|~~~)[^\n]*\n[\s\S]*?^(?:```|~~~)[^\n]*$/gm, '')
    .replace(/`[^`\n]*`/g, '');
}

for (const full of docs.keys()) {
  const text = stripCode(fs.readFileSync(full, 'utf8'));
  let m;
  while ((m = LINK_RE.exec(text)) !== null) {
    const isImage = m[1] === '!';
    const target = m[3];
    if (/^(https?:)?\/\//i.test(target) || /^mailto:/i.test(target)) {
      externalLinks++;
      continue;
    }
    if (target.startsWith('#')) continue;
    const [p] = target.split('#');
    if (!p) continue;

    if (isImage) {
      imageLinks++;
      // 图片路径：/img/... 解析到 static/ 下；相对路径按当前 Markdown 所在目录解析
      const abs = p.startsWith('/')
        ? path.join(STATIC, decodeURIComponent(p).replace(/^\/+/, ''))
        : path.resolve(path.dirname(full), decodeURIComponent(p));
      if (!fs.existsSync(abs)) {
        fail(`${rel(full)}：图片文件不存在 -> ${target}`);
      }
      continue;
    }

    internalLinks++;

    if (p.startsWith('/')) {
      const rest = p.replace(/^\/+/, '').replace(/^docs\//, '');
      if (!docTargetExists(rest) && !fs.existsSync(path.join(STATIC, rest))) {
        fail(`${rel(full)}：站内绝对链接失效 -> ${target}`);
      }
      continue;
    }

    const abs = path.resolve(path.dirname(full), decodeURIComponent(p));
    if (
      !fs.existsSync(abs) &&
      !fs.existsSync(`${abs}.md`) &&
      !fs.existsSync(`${abs}.mdx`)
    ) {
      fail(`${rel(full)}：相对链接失效 -> ${target}`);
    }
  }
}

/* --------------------------- sidebar 层级预览 --------------------------- */

function buildTree(dir) {
  const cat = categories.get(dir);
  const entries = [];

  for (const [full, info] of docs) {
    if (path.dirname(full) === dir) {
      // Docusaurus 在侧边栏优先显示 sidebar_label，没有时才回退到 title
      entries.push({ position: info.position, label: info.sidebarLabel || info.title, kind: 'doc' });
    }
  }
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    const info = buildTree(path.join(dir, e.name));
    entries.push({ position: info.position, label: info.label, kind: 'category', children: info.children });
  }

  entries.sort(
    (a, b) => a.position - b.position || String(a.label).localeCompare(String(b.label)),
  );

  return {
    label: cat ? cat.label : path.basename(dir),
    position: cat && Number.isInteger(cat.position) ? cat.position : Number.MAX_SAFE_INTEGER,
    children: entries,
  };
}

function renderTree(node, prefix = '', isLast = true, isRoot = true) {
  const lines = [];
  if (!isRoot) {
    lines.push(`${prefix}${isLast ? '└─ ' : '├─ '}${node.label}`);
  }
  const childPrefix = isRoot ? '' : prefix + (isLast ? '   ' : '│  ');
  const children = node.children || [];
  children.forEach((child, i) => {
    lines.push(...renderTree(child, childPrefix, i === children.length - 1, false));
  });
  return lines;
}

/* -------------------------------- 输出 --------------------------------- */

const catCount = categories.size;
console.log(`DockStart Documentation —— ${ENGLISH ? '英文' : '中文'}结构检查`);
console.log(`项目根目录：${ROOT}`);
console.log(
  `统计：${docs.size} 个 Markdown 页面，${catCount} 个分类目录，` +
    `${internalLinks} 个站内链接，${externalLinks} 个外部链接，${imageLinks} 张图片`,
);
console.log('');

if (SHOW_TREE) {
  console.log('sidebar 预览（由 docs/ + _category_.json + sidebar_position 推导）：');
  for (const line of renderTree(buildTree(DOCS))) console.log(`  ${line}`);
  console.log('');
}

if (warnings.length) {
  console.log(`警告 ${warnings.length} 条：`);
  for (const w of warnings) console.log(`  [warn]  ${w}`);
  console.log('');
}

if (errors.length) {
  console.log(`错误 ${errors.length} 条：`);
  for (const e of errors) console.log(`  [error] ${e}`);
  console.log('');
  console.log('结果：FAILED');
  process.exit(1);
}

console.log('结果：OK（无 error）');
